### ISSUE TITLE
I have problems using the process

### ISSUE THREAD

**Issue by hooray** [eight04/rollup-plugin-external-globals#23]
```
[rollup-plugin-external-globals] Assigning to rvalue (1:1)
file: C:/Users/hoora/Desktop/fap/src/layout/index.vue?vue&type=style&index=0&scoped=true&lang.scss:1:1
error during build:
SyntaxError: Assigning to rvalue (1:1)
    at Parser.pp$4.raise (C:\Users\hoora\Desktop\fap\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:16954:13)
    at Parser.pp$2.toAssignable (C:\Users\hoora\Desktop\fap\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:15616:12)
    at Parser.pp$3.parseMaybeAssign (C:\Users\hoora\Desktop\fap\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:15982:21)
    at Parser.pp$3.parseExprList (C:\Users\hoora\Desktop\fap\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:16835:18)
    at Parser.pp$3.parseExprAtom (C:\Users\hoora\Desktop\fap\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:16303:26)
    at Parser.pp$3.parseExprSubscripts (C:\Users\hoora\Desktop\fap\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:16126:19)
    at Parser.pp$3.parseMaybeUnary (C:\Users\hoora\Desktop\fap\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:16092:17)
    at Parser.pp$3.parseExprOps (C:\Users\hoora\Desktop\fap\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:16025:19)
    at Parser.pp$3.parseMaybeConditional (C:\Users\hoora\Desktop\fap\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:16008:19)
    at Parser.pp$3.parseMaybeAssign (C:\Users\hoora\Desktop\fap\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:15976:19)
    at Parser.pp$3.parseExpression (C:\Users\hoora\Desktop\fap\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:15940:19)
    at Parser.pp$1.parseStatement (C:\Users\hoora\Desktop\fap\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:14652:45)
    at Parser.pp$1.parseTopLevel (C:\Users\hoora\Desktop\fap\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:14519:21)
    at Parser.parse (C:\Users\hoora\Desktop\fap\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:14311:15)
    at Function.parse (C:\Users\hoora\Desktop\fap\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:14342:35)
    at Graph.contextParse (C:\Users\hoora\Desktop\fap\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:20323:38)
 ERROR  Command failed with exit code 1.
```

I encountered this problem in the process of using the code, when I deleted the code a little bit, I found that the error was caused by this code, but what confused me is that this code is also used in other pages, but only in this page will report an error, after commenting out and then run everything is normal

```scss
     @include themeify {
         color: themed('g-header-color');
         background-color: themed('g-header-bg');
     }
```

**Comment by eight04** [comment]
Make sure to use vue plugin before this one.

**Comment by hooray** [comment]
我发现了另一个bug，我在项目里使用 remixicon 这个库，打包的时候就会报错，我用vite复现的这个问题，如果可以的话，麻烦看下这个[仓库](https://github.com/hooray/vite-vue-cdn-demo)。安装好依赖后，运行 `pnpm build`会报下面这段错误

```
[rollup-plugin-external-globals] Unexpected character '@' (11:0)
file: C:/Users/hoora/Desktop/test/vite-project/node_modules/.pnpm/registry.nlark.com+remixicon@2.5.0/node_modules/remixicon/fonts/remixicon.css:11:0
error during build:
SyntaxError: Unexpected character '@' (11:0)
    at Parser.pp$4.raise (C:\Users\hoora\Desktop\test\vite-project\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:16954:13)
    at Parser.pp$9.getTokenFromCode (C:\Users\hoora\Desktop\test\vite-project\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:18766:8)
    at Parser.pp$9.readToken (C:\Users\hoora\Desktop\test\vite-project\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:18450:15)
    at Parser.pp$9.nextToken (C:\Users\hoora\Desktop\test\vite-project\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:18441:15)
    at Parser.parse (C:\Users\hoora\Desktop\test\vite-project\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:14310:8)
    at Function.parse (C:\Users\hoora\Desktop\test\vite-project\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:14342:35)
    at Graph.contextParse (C:\Users\hoora\Desktop\test\vite-project\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:20323:38)
    at Object.transform (C:\Users\hoora\Desktop\test\vite-project\node_modules\.pnpm\registry.nlark.com+rollup-plugin-external-globals@0.6.1\node_modules\rollup-plugin-external-globals\index.js:37:22)
    at C:\Users\hoora\Desktop\test\vite-project\node_modules\.pnpm\registry.nlark.com+rollup@2.55.1\node_modules\rollup\dist\shared\rollup.js:20197:25
```

**Comment by eight04** [comment]
你貼出來的兩段訊息都告訴你這是 parse 程式碼的錯誤，位於 https://github.com/eight04/rollup-plugin-external-globals/blob/30b2534566e3a67b253c9a2e6f636289b7d1b7b3/index.js#L37
發生錯誤的檔案分別是
```
C:/Users/hoora/Desktop/fap/src/layout/index.vue?vue&type=style&index=0&scoped=true&lang.scss:1:1
```
和
```
C:/Users/hoora/Desktop/test/vite-project/node_modules/.pnpm/registry.nlark.com+remixicon@2.5.0/node_modules/remixicon/fonts/remixicon.css:11:0
```
我猜測，你在使用這個 external-globals 插件之前，並沒有以其它的插件處理 .vue 或 .css 檔案，以致於 rollup parse 了 .vue/.css 檔案後報錯。

兩個建議︰

1. 在使用 external-globals 之前，務必先使用 vue/css 的插件。我不知道 vite 是如何運作的，也許它內建了 css 插件？也許你應該查詢要如何在 vite 中指定插件的順序。
2. 讓 external-globals 只處理 js 檔︰
    ```js
    externalGlobals({
      vue: 'Vue'
    }, {
      include: ["**/*.js"] // 或是 ["**/*.js", "**/*.vue"] 因為你的專案似乎有 .vue 檔案
    })
    ```

**Comment by hooray** [comment]
好的，感谢，我明天再尝试解决下看看
